import { readFile, writeFile } from 'node:fs/promises';
import { Script } from 'node:vm';
import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone';
import hostSchema from '../../schemas/preview-host.schema.json';

export async function generatePreviewRuntime(): Promise<string> {
  const ajv = new Ajv({ code: { source: true, esm: true, lines: true } });
  ajv.compile(hostSchema);

  const module = standaloneCode(ajv, { validateHostMessage: hostSchema.$id });
  const declaration = 'export const validateHostMessage =';

  if (!module.includes(declaration)) throw new Error('Expected a named validateHostMessage export from AJV.');

  const validator = module.replace(declaration, 'const validateHostMessage =');

  if (/\brequire\s*\(|\bimport\s*\(/.test(validator)) throw new Error('Preview validator must be self-contained; external helpers and modules are unsupported.');

  // Static imports or leftover exports are invalid in the classic-script runtime.
  new Script(validator, { filename: 'preview-host-validator.js' });

  const source = await readFile(new URL('../src/preview/runtime-source.js', import.meta.url), 'utf8');

  return `/* Generated by scripts/build-preview-runtime.ts.
 * Edit src/preview/runtime-source.js or ../schemas/preview-host.schema.json,
 * then run bun scripts/build-preview-runtime.ts from frontend/.
 */
(() => {
${validator.trimEnd()}
${source.trimEnd()}
})();
`;
}

if (import.meta.main) {
  await writeFile(new URL('../src/preview/runtime.js', import.meta.url), await generatePreviewRuntime());
}
